//*************************************************************************
//
//    Copyright (c) 2013 Tallan Inc.  All rights reserved. 
//
//    Use of this sample source code is subject to the terms of the Microsoft Limited Public License
//    at http://msdn.microsoft.com/en-us/cc300389.aspx#P and is provided AS-IS. 
//
//    For more information about Tallan, visit our website, http://tallan.com/.     
//
//    To see the topic that inspired this sample app, go to http://msdn.microsoft.com/en-us/library/windows/apps/jj635241. 
//
//*************************************************************************


/// <reference path="ms-appx://Microsoft.WinJS.1.0/js/base.js" />

var LOADING_DELAY = 500;
if (Windows.ApplicationModel.DesignMode.designModeEnabled) {
    LOADING_DELAY = 0;
}

(function servicesInit(WinJS) {
    "use strict";

    var liveIdInfo = { first_name: "John", last_name: "Doe", emails: { preferred: "john@example.com" } };
    var products;
    (function SetProductsSampleData() {
        /// <summary>
        /// Gets a JSON for an offline catalog.  This data is the same as the data found on the Shopping.WebApi project.
        /// This is wrapped in a self executing function rather then just being an inline variable to support epanding/collapsing
        /// in Visual Studio an improve overall readability.
        /// </summary>
        products = [
	{
	    "ProductId": "1",
	    "Name": "Fedora",
	    "Area": "For the Head",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/3_head.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/head.png",
	    "Category": "Hats",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Hat/7_zoom.png",
	    "Price": "29.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Hat/7_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Hat/7_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Hat/7_tb.png",
	    "Rating": "3",
	    "Featured": "TRUE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jane Doe",
	    "Review1Title": "Consectetur Adipisicing Elit",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jamie Doe",
	    "Review2Title": "Lorem Ipsum Dolor",
	    "Review3Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review3Author": "Jim Doe",
	    "Review3Title": "Lorem Ipsum Dolor Sit Amet",
	    "": ""
	},
		{
		    "ProductId": "2",
		    "Name": "Men's Red Scarf",
		    "Area": "Around the Neck",
		    "AreaImage": "ms-appx:///images/OfflineImages/Areas/5_neck.png",
		    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/neck.png",
		    "Category": "Scarves",
		    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Scarf/6_zoom.png",
		    "Price": "24.99",
		    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
		    "Image": "ms-appx:///images/OfflineImages/Products/Scarf/6_product.png",
		    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Scarf/6_browse.png",
		    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Scarf/6_tb.png",
		    "Rating": "4.5",
		    "Featured": "TRUE",
		    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
		    "Review1Author": "John Doe",
		    "Review1Title": "Lorem Ipsum Dolor",
		    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
		    "Review2Author": "Jim Doe",
		    "Review2Title": "Lorem Ipsum Dolor Sit Amet",
		    "Review3Text": "",
		    "Review3Author": "",
		    "Review3Title": "",
		    "": ""
		},
	{
	    "ProductId": "3",
	    "Name": "Black Tie",
	    "Area": "Around the Neck",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/5_neck.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/neck.png",
	    "Category": "Ties",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Tie/7_zoom.png",
	    "Price": "25.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Tie/7_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Tie/7_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Tie/7_tb.png",
	    "Rating": "4",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jim Doe",
	    "Review1Title": "Lorem Ipsum Dolor Sit Amet",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "John Doe",
	    "Review2Title": "Sed Do Eiumond Tempor",
	    "Review3Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review3Author": "Jack Doe",
	    "Review3Title": "Consectetur Adipisicing Elit",
	    "": ""
	},
	{
	    "ProductId": "4",
	    "Name": "Soft Red Sweater",
	    "Area": "Over the Shoulder",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_shoulder.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/shoulder.png",
	    "Category": "Sweaters",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Sweater/6_zoom.png",
	    "Price": "69.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Sweater/6_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Sweater/6_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Sweater/6_tb.png",
	    "Rating": "5",
	    "Featured": "TRUE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jack Doe",
	    "Review1Title": "Lorem Ipsum Dolor",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jessica Doe",
	    "Review2Title": "Lorem Ipsum Dolor Sit Amet",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "5",
	    "Name": "Brown Blazer",
	    "Area": "Over the Shoulder",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_shoulder.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/shoulder.png",
	    "Category": "Coats & Outerware",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Blazer/2_zoom.png",
	    "Price": "359.95",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Blazer/2_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Blazer/2_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Blazer/2_tb.png",
	    "Rating": "4.5",
	    "Featured": "FALSE",
	    "Review1Text": "",
	    "Review1Author": "",
	    "Review1Title": "Consectetur Adipisicing Elit",
	    "Review2Text": "",
	    "Review2Author": "",
	    "Review2Title": "",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "6",
	    "Name": "Blue Blazer",
	    "Area": "Over the Shoulder",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_shoulder.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/shoulder.png",
	    "Category": "Coats & Outerware",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Blazer/5_zoom.png",
	    "Price": "299.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Blazer/5_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Blazer/5_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Blazer/5_tb.png",
	    "Rating": "4.5",
	    "Featured": "TRUE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "John Doe",
	    "Review1Title": "Sed Do Eiumond Tempor",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jim Doe",
	    "Review2Title": "Consectetur Adipisicing Elit",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},

	{
	    "ProductId": "7",
	    "Name": "Black Blazer",
	    "Area": "Over the Shoulder",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_shoulder.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/shoulder.png",
	    "Category": "Coats & Outerware",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Blazer/7_zoom.png",
	    "Price": "399.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Blazer/7_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Blazer/7_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Blazer/7_tb.png",
	    "Rating": "4.5",
	    "Featured": "TRUE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jamie Doe",
	    "Review1Title": "Lorem Ipsum Dolor",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jane Doe",
	    "Review2Title": "Lorem Ipsum Dolor Sit Amet",
	    "Review3Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review3Author": "John Doe",
	    "Review3Title": "Sed Do Eiumond Tempor",
	    "": ""
	},
    	{
    	    "ProductId": "8",
    	    "Name": "Denim Jacket",
    	    "Area": "Over the Shoulder",
    	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_shoulder.png",
    	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/shoulder.png",
    	    "Category": "Jackets",
    	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Jacket/5_zoom.png",
    	    "Price": "549.99",
    	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
    	    "Image": "ms-appx:///images/OfflineImages/Products/Jacket/5_product.png",
    	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Jacket/5_browse.png",
    	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Jacket/5_tb.png",
    	    "Rating": "4",
    	    "Featured": "FALSE",
    	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
    	    "Review1Author": "Jane Doe",
    	    "Review1Title": "Lorem Ipsum Dolor Sit Amet",
    	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
    	    "Review2Author": "Jamie Doe",
    	    "Review2Title": "Sed Do Eiumond Tempor",
    	    "Review3Text": "",
    	    "Review3Author": "",
    	    "Review3Title": "",
    	    "": ""
    	},
	{
	    "ProductId": "9",
	    "Name": "Red Shirt",
	    "Area": "Over the Shoulder",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_shoulder.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/shoulder.png",
	    "Category": "Shirts",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Shirt/6_zoom.png",
	    "Price": "69.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Shirt/6_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Shirt/6_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Shirt/6_tb.png",
	    "Rating": "4",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jim Doe",
	    "Review1Title": "Consectetur Adipisicing Elit",
	    "Review2Text": "",
	    "Review2Author": "",
	    "Review2Title": "",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "10",
	    "Name": "White Shirt",
	    "Area": "Over the Shoulder",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_shoulder.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/shoulder.png",
	    "Category": "Shirts",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Shirt/1_zoom.png",
	    "Price": "89.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Shirt/1_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Shirt/1_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Shirt/1_tb.png",
	    "Rating": "4",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jamie Doe",
	    "Review1Title": "Sed Do Eiumond Tempor",
	    "Review2Text": "",
	    "Review2Author": "",
	    "Review2Title": "",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "11",
	    "Name": "Leather Work Jacket",
	    "Area": "Over the Shoulder",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_shoulder.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/shoulder.png",
	    "Category": "Jackets",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Jacket/7_zoom.png",
	    "Price": "339.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Jacket/7_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Jacket/7_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Jacket/7_tb.png",
	    "Rating": "4",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jessica Doe",
	    "Review1Title": "Lorem Ipsum Dolor Sit Amet",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jack Doe",
	    "Review2Title": "Sed Do Eiumond Tempor",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "12",
	    "Name": "Green Jacket",
	    "Area": "Over the Shoulder",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_shoulder.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/shoulder.png",
	    "Category": "Jackets",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Jacket/3_zoom.png",
	    "Price": "379.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Jacket/3_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Jacket/3_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Jacket/3_tb.png",
	    "Rating": "4",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "John Doe",
	    "Review1Title": "Lorem Ipsum Dolor",
	    "Review2Text": "",
	    "Review2Author": "",
	    "Review2Title": "",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "13",
	    "Name": "Tan Suede Jacket",
	    "Area": "Over the Shoulder",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_shoulder.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/shoulder.png",
	    "Category": "Jackets",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Jacket/2_zoom.png",
	    "Price": "299.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Jacket/2_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Jacket/2_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Jacket/2_tb.png",
	    "Rating": "4",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jane Doe",
	    "Review1Title": "Consectetur Adipisicing Elit",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jamie Doe",
	    "Review2Title": "Lorem Ipsum Dolor",
	    "Review3Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review3Author": "Jim Doe",
	    "Review3Title": "Sed Do Eiumond Tempor",
	    "": ""
	},
	{
	    "ProductId": "14",
	    "Name": "Coat",
	    "Area": "Over the Shoulder",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_shoulder.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/shoulder.png",
	    "Category": "Jackets",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Jacket/6_zoom.png",
	    "Price": "299.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Jacket/6_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Jacket/6_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Jacket/6_tb.png",
	    "Rating": "4",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jack Doe",
	    "Review1Title": "Sed Do Eiumond Tempor",
	    "Review2Text": "",
	    "Review2Author": "",
	    "Review2Title": "",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "15",
	    "Name": "Blue Jeans",
	    "Area": "Down the Leg",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/2_leg.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/leg.png",
	    "Category": "Jeans",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Jeans/1_zoom.png",
	    "Price": "99.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Jeans/1_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Jeans/1_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Jeans/1_tb.png",
	    "Rating": "4",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jim Doe",
	    "Review1Title": "Lorem Ipsum Dolor Sit Amet",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "John Doe",
	    "Review2Title": "Sed Do Eiumond Tempor",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "16",
	    "Name": "Faded Blue Jeans",
	    "Area": "Down the Leg",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/2_leg.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/leg.png",
	    "Category": "Jeans",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Jeans/5_zoom.png",
	    "Price": "89.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Jeans/5_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Jeans/5_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Jeans/5_tb.png",
	    "Rating": "4",
	    "Featured": "TRUE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jamie Doe",
	    "Review1Title": "Lorem Ipsum Dolor",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jane Doe",
	    "Review2Title": "Consectetur Adipisicing Elit",
	    "Review3Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review3Author": "Jack Doe",
	    "Review3Title": "Sed Do Eiumond Tempor",
	    "": ""
	},
	{
	    "ProductId": "17",
	    "Name": "Black Jeans",
	    "Area": "Down the Leg",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/2_leg.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/leg.png",
	    "Category": "Jeans",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Jeans/7_zoom.png",
	    "Price": "79.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Jeans/7_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Jeans/7_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Jeans/7_tb.png",
	    "Rating": "4",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jessica Doe",
	    "Review1Title": "Consectetur Adipisicing Elit",
	    "Review2Text": "",
	    "Review2Author": "",
	    "Review2Title": "",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "18",
	    "Name": "Green Jeans",
	    "Area": "Down the Leg",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/2_leg.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/leg.png",
	    "Category": "Jeans",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Jeans/3_zoom.png",
	    "Price": "59.95",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Jeans/3_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Jeans/3_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Jeans/3_tb.png",
	    "Rating": "2",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "John Doe",
	    "Review1Title": "Sed Do Eiumond Tempor",
	    "Review2Text": "",
	    "Review2Author": "",
	    "Review2Title": "",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "19",
	    "Name": "Black Sunglasses",
	    "Area": "For the Head",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/3_head.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/head.png",
	    "Category": "Sunglasses",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Sunglasses/7_zoom.png",
	    "Price": "199.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Sunglasses/7_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Sunglasses/7_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Sunglasses/7_tb.png",
	    "Rating": "4",
	    "Featured": "TRUE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jane Doe",
	    "Review1Title": "Lorem Ipsum Dolor Sit Amet",
	    "Review2Text": "",
	    "Review2Author": "",
	    "Review2Title": "",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "20",
	    "Name": "Brown Shades",
	    "Area": "For the Head",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/3_head.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/head.png",
	    "Category": "Sunglasses",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Sunglasses/8_zoom.png",
	    "Price": "299.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Sunglasses/8_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Sunglasses/8_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Sunglasses/8_tb.png",
	    "Rating": "5",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jack Doe",
	    "Review1Title": "Lorem Ipsum Dolor",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jessica Doe",
	    "Review2Title": "Sed Do Eiumond Tempor",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "21",
	    "Name": "Blue Hat",
	    "Area": "For the Head",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/3_head.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/head.png",
	    "Category": "Hats",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Hat/5_zoom.png",
	    "Price": "25.95",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Hat/5_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Hat/5_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Hat/5_tb.png",
	    "Rating": "3",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jim Doe",
	    "Review1Title": "Consectetur Adipisicing Elit",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "John Doe",
	    "Review2Title": "Lorem Ipsum Dolor",
	    "Review3Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review3Author": "Jamie Doe",
	    "Review3Title": "Sed Do Eiumond Tempor",
	    "": ""
	},
	{
	    "ProductId": "22",
	    "Name": "Grey Tie",
	    "Area": "Around the Neck",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/5_neck.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/neck.png",
	    "Category": "Ties",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Tie/4_zoom.png",
	    "Price": "34.95",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Tie/4_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Tie/4_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Tie/4_tb.png",
	    "Rating": "2",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jamie Doe",
	    "Review1Title": "Sed Do Eiumond Tempor",
	    "Review2Text": "",
	    "Review2Author": "",
	    "Review2Title": "",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "23",
	    "Name": "Suede Shoes",
	    "Area": "On the Sole",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_sole.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/sole.png",
	    "Category": "Shoes",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Shoes/2_zoom.png",
	    "Price": "45.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Shoes/2_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Shoes/2_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Shoes/2_tb.png",
	    "Rating": "4",
	    "Featured": "TRUE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jessica Doe",
	    "Review1Title": "Lorem Ipsum Dolor Sit Amet",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jack Doe",
	    "Review2Title": "Sed Do Eiumond Tempor",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "24",
	    "Name": "Dress Shoes",
	    "Area": "On the Sole",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_sole.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/sole.png",
	    "Category": "Shoes",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Shoes/7_zoom.png",
	    "Price": "59.95",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Shoes/7_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Shoes/7_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Shoes/7_tb.png",
	    "Rating": "5",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "John Doe",
	    "Review1Title": "Lorem Ipsum Dolor",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jim Doe",
	    "Review2Title": "Lorem Ipsum Dolor Sit Amet",
	    "Review3Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review3Author": "Jane Doe",
	    "Review3Title": "Consectetur Adipisicing Elit",
	    "": ""
	},
	{
	    "ProductId": "25",
	    "Name": "Black Loafers",
	    "Area": "On the Sole",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_sole.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/sole.png",
	    "Category": "Loafers",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Loafers/7_zoom.png",
	    "Price": "19.95",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Loafers/7_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Loafers/7_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Loafers/7_tb.png",
	    "Rating": "2",
	    "Featured": "TRUE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jane Doe",
	    "Review1Title": "Consectetur Adipisicing Elit",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jamie Doe",
	    "Review2Title": "Sed Do Eiumond Tempor",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "26",
	    "Name": "Blue Sneakers",
	    "Area": "On the Sole",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_sole.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/sole.png",
	    "Category": "Sneakers",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Sneakers/5_zoom.png",
	    "Price": "89.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Sneakers/5_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Sneakers/5_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Sneakers/5_tb.png",
	    "Rating": "5",
	    "Featured": "TRUE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jack Doe",
	    "Review1Title": "Sed Do Eiumond Tempor",
	    "Review2Text": "",
	    "Review2Author": "",
	    "Review2Title": "",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "27",
	    "Name": "Brown Sneakers",
	    "Area": "On the Sole",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_sole.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/sole.png",
	    "Category": "Sneakers",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Sneakers/2_zoom.png",
	    "Price": "79.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Sneakers/2_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Sneakers/2_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Sneakers/2_tb.png",
	    "Rating": "3",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jim Doe",
	    "Review1Title": "Lorem Ipsum Dolor Sit Amet",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "John Doe",
	    "Review2Title": "Consectetur Adipisicing Elit",
	    "Review3Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review3Author": "Jessica Doe",
	    "Review3Title": "Sed Do Eiumond Tempor",
	    "": ""
	},
	{
	    "ProductId": "28",
	    "Name": "Gray Scarf",
	    "Area": "Around the Neck",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/5_neck.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/neck.png",
	    "Category": "Scarves",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Scarf/1_zoom.png",
	    "Price": "29.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Scarf/1_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Scarf/1_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Scarf/1_tb.png",
	    "Rating": "4.5",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "John Doe",
	    "Review1Title": "Lorem Ipsum Dolor",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jim Doe",
	    "Review2Title": "Lorem Ipsum Dolor Sit Amet",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "29",
	    "Name": "Blue Tie",
	    "Area": "Around the Neck",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/5_neck.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/neck.png",
	    "Category": "Ties",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Tie/5_zoom.png",
	    "Price": "25.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Tie/5_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Tie/5_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Tie/5_tb.png",
	    "Rating": "5",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jack Doe",
	    "Review1Title": "Sed Do Eiumond Tempor",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jessica Doe",
	    "Review2Title": "Consectetur Adipisicing Elit",
	    "Review3Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review3Author": "Jane Doe",
	    "Review3Title": "Lorem Ipsum Dolor Sit Amet",
	    "": ""
	},
	{
	    "ProductId": "30",
	    "Name": "Soft White Sweater",
	    "Area": "Over the Shoulder",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/7_shoulder.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/shoulder.png",
	    "Category": "Sweaters",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Sweater/1_zoom.png",
	    "Price": "79.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Sweater/1_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Sweater/1_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Sweater/1_tb.png",
	    "Rating": "5",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jack Doe",
	    "Review1Title": "Lorem Ipsum Dolor",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "Jessica Doe",
	    "Review2Title": "Lorem Ipsum Dolor Sit Amet",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	},
	{
	    "ProductId": "31",
	    "Name": "Khakis",
	    "Area": "Down the Leg",
	    "AreaImage": "ms-appx:///images/OfflineImages/Areas/2_leg.png",
	    "AreaAppBarImage": "ms-appx:///images/OfflineImages/Appbar/leg.png",
	    "Category": "Pants",
	    "CategoryImage": "ms-appx:///images/OfflineImages/Products/Pants/1_zoom.png",
	    "Price": "24.99",
	    "Description": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Image": "ms-appx:///images/OfflineImages/Products/Pants/1_product.png",
	    "XLargeImage": "ms-appx:///images/OfflineImages/Products/Pants/1_browse.png",
	    "ThumbnailImage": "ms-appx:///images/OfflineImages/Products/Pants/1_tb.png",
	    "Rating": "4",
	    "Featured": "FALSE",
	    "Review1Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review1Author": "Jim Doe",
	    "Review1Title": "Lorem Ipsum Dolor Sit Amet",
	    "Review2Text": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor.",
	    "Review2Author": "John Doe",
	    "Review2Title": "Sed Do Eiumond Tempor",
	    "Review3Text": "",
	    "Review3Author": "",
	    "Review3Title": "",
	    "": ""
	}
        ];

        _.each(products, function(p) {
            p.RatingCount = 50;
            p.Reviews = [];
            for (var i = 0; i < 14; i++) {
                p.Reviews.push({ Author: "unknown", Title: "Review " + i + 1, Comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiumod tempor." });
            }
        });
    })();
    
    function getCatalogVersionAsync() {
        return WinJS.Promise.as(1);
    }

    function getCatalogAsync() {
        var catalog = {
            version: 1,
            name: "Head to Toe",
            products: products
        };
        if (LOADING_DELAY == 0) {
            return WinJS.Promise.as(catalog);
        }

        var completed;
        var promise = new WinJS.Promise(function(c) {
            completed = c;
        });
        setTimeout(function () {
            completed(catalog);
        }, LOADING_DELAY);
        return promise;
    }

    function getProductAsync(id) {
        var product = _.find(products, function (p) {
            return p.ProductId == id;
        });
        return WinJS.Promise.as(product);
    }

    function getLiveIdAsync() {
        return WinJS.Promise.as(liveIdInfo);
    }

    function getCartAsync(id) {
        return createCartAsync();
    }

    function createCartAsync() {
        var cart = {
            Id: 1,
            Email: liveIdInfo.emails.preferred,
            BillingAddress: {
                FirstName: liveIdInfo.first_name,
                LastName: liveIdInfo.last_name,
                Line1: '',
                Line2: '',
                City: '',
                State: '',
                Zip: ''
            },
            ShippingAddress: {
                FirstName: '',
                LastName: '',
                Line1: '',
                Line2: '',
                City: '',
                State: '',
                Zip: ''
            },
            PaymentInfo: {
                CardType: '',
                CardNumber: '',
                CvvCode: '',
                ExpirationMonth: '',
                ExpirationYear: ''
            },
            Items: [],
            Terms: false,
            SameAddresses: false
        };

        return WinJS.Promise.as(cart);
    }

    function updateCartAsync(cart) {
        return WinJS.Promise.as(cart);
    }

    var services =
    {
        getCatalogVersionAsync: getCatalogVersionAsync,
        getCatalogAsync: getCatalogAsync,

        getProductAsync: getProductAsync,

        getLiveIdAsync: getLiveIdAsync,

        getCartAsync: getCartAsync,
        createCartAsync: createCartAsync,
        updateCartAsync: updateCartAsync
    };

    WinJS.Namespace.define("Shopping.Services.Offline", services);
})(WinJS);